environment:
  - "FORCE_COLOR=1"
processes:

  npmInstall:
    command: npm install --color=always

  vite-dev:
    command: npx vite dev --port 5173 --strictPort
    ports:
      - 5173:5173
    dependsOn:
       npmInstall:
          condition: process_completed_successfully

  mill-watch:
    command: mill --color true --watch frontend.fastLinkJS
